# Generated by Django 6.0.2 on 2026-02-26 11:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail_alter_lessonmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmedia',
            name='external_url',
            field=models.URLField(blank=True, help_text='Use for videos/PDFs hosted externally', null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
