# Generated by Django 6.0.2 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonmedia_external_url_alter_lessonmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmedia',
            name='external_url',
            field=models.URLField(blank=True, help_text='Use for videos/PDFs hosted externally or YouTube links', null=True, verbose_name='External URL'),
        ),
    ]
