# Generated by Django 6.0.2 on 2026-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_question_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
