# Generated by Django 6.0.2 on 2026-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quizattempt_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
